### ISSUE TITLE
Link Broken of Setup ruODK

### ISSUE THREAD

**Issue by iamnarendrasingh** [dbca-wa/rOzCBI#3]
## Problem

I started exploring this project and when I am on this page : https://dbca-wa.github.io/rOzCBI/articles/analysis.html , found that link for Setup ruODK "https://dbca-wa.github.io/rOzCBI/articles/analysis.html#:~:text=every%20data%20analyst.-,Setup%20ruODK,-For%20details%2C%20refer" is broken and saying error 404.

## Reproducible example

```{r}
# insert reprex here
```

<details>
<summary><strong>Session Info</strong></summary>

```{r}
# utils::sessionInfo()
```
</details>

**Comment by florianm** [comment]
Thanks for the report and for checking out rOzCBI, @iamnarendrasingh!

Indeed the setup link is outdated, we've moved to another server. Internally, we're also moving to new form versions and I'm in the process of upgrading rOzCBI to work with those new form versions.

Since the data is captured by DBCA and we don't offer a public demo server, the vignette targets DBCA users and analysts.

If you wish to test out rOzCBI for your own burn grading evaluations (or as a template for a standalone R package for a given ODK campaign), feel free to use the supplied form BurnGrading01 which you can find at https://github.com/dbca-wa/rOzCBI/tree/master/inst/odk on your own server, where you can capture example data (without sending it into DBCA production data :-) ) and analyse that using your own server credentials. From an ODK/ruODK perspective, it's pretty standard. A form, some example submissions, a few R functions to calculate a value from submission data, and a leaflet map to show annotated submissions.
You can get similar value out of the [ruODK vignette on spatial data](https://docs.ropensci.org/ruODK/articles/spatial.html).

I will adjust the vignette to explain the above.
Thanks for your interest in rOzCBI!
